### ISSUE TITLE
Android app sha256 signature is not supported as origin

### ISSUE THREAD

**Issue by pitampoudel** [Yubico/java-webauthn-server#332] opened 2023-11-25 09:26 UTC
Android recommends implementing that way to put the sha256 signature as the origin but the yubico.webauthn library does not supports that

```
TRACE com.yubico.webauthn.OriginMatcher - isAllowed(android:apk-key-hash:qvuLMyLL__vtfHay6y_KGGHYL5Qkkf5aufucFCAtWVE, [https://pitampoudel.com.np], false, false)
DEBUG com.yubico.webauthn.OriginMatcher - Origin in client data is not a valid URL; will only match exactly: android:apk-key-hash:qvuLMyLL__vtfHay6y_KGGHYL5Qkkf5aufucFCAtWVE
DEBUG com.yubico.webauthn.OriginMatcher - No match: android:apk-key-hash:qvuLMyLL__vtfHay6y_KGGHYL5Qkkf5aufucFCAtWVE != https://pitampoudel.com.np
com.yubico.webauthn.exception.RegistrationFailedException: java.lang.IllegalArgumentException: Incorrect origin: android:apk-key-hash:qvuLMyLL__vtfHay6y_KGGHYL5Qkkf5aufucFCAtWVE
```

**Comment by pitampoudel** [comment] 2023-11-25 09:31
please take a look at 
[FinishRegistrationSteps.java](https://github.com/Yubico/java-webauthn-server/tree/main/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishRegistrationSteps.java)

**Comment by emlun** [comment] 2023-11-25 14:25
Hi! This looks like a duplicate of #159, is it?

**Comment by pitampoudel** [comment] 2023-11-25 14:47
Yes. Thank you!

**Comment by emlun** [comment] 2023-11-25 14:59
Great! But since this has come up a couple of times now, we should probably mention this in the usage instructions. I'll keep the issue open to track that.

**Closed** 2023-11-27 15:25 UTC
