### ISSUE TITLE
Maven dependency convergence issue

### ISSUE THREAD

**Issue by FlattestGuitar** [Yubico/java-webauthn-server#36] opened 2019-09-03 08:40 UTC
Maven Enforcer will flag the `yubico:webauthn` package because of conflicting versions of its dependencies. This will make many pipelines out there fail without a patchwork fix.
```
[WARNING] 
Dependency convergence error for com.github.peteroupc:numbers:0.2.1 paths to dependency are:
 +-com.yubico:webauthn-server-core:1.3.0
   +-com.augustcellars.cose:cose-java:0.9.4
     +-com.upokecenter:cbor:2.4.1
       +-com.github.peteroupc:numbers:0.2.1
and
 +-com.yubico:webauthn-server-core:1.3.0
   +-com.augustcellars.cose:cose-java:0.9.4
     +-com.github.peteroupc:numbers:0.3.0
```
A potential fix would be excluding the `peteroupc:numbers` package from one of the modules, but I don't know much about maven, so maybe there's a better solution?

**Comment by emlun** [comment] 2019-09-03 10:39
Thanks for the report! Looks like this is an issue with the transitive dependencies from `cose-java`. I'm also not familiar with Maven Enforcer, but maybe this can be resolved by bumping the dependency version.

**Comment by FlattestGuitar** [comment] 2019-09-16 12:55
Sorry for the late response. I tried to test it but I'm having some trouble building my project.

```
Error:(4, 1) java: cannot access com.yubico.internal.util.json.JsonStringSerializable
class file for com.yubico.internal.util.json.JsonStringSerializable not found
```

That `(4,1)` points to one of my static imports:
`import static com.yubico.webauthn.data.PublicKeyCredentialType.PUBLIC_KEY;`.

Is this my fault or yours? :thinking:

**Comment by emlun** [comment] 2019-09-16 13:24
That looks like the dependency `com.yubico:yubico-util` is missing. Which is strange, because it should be resolved automatically by the build system...

**Comment by ralscha** [comment] 2019-09-30 04:36
The problem is that `yubico-util` is defined with scope `runtime`, thus not available at compile time.
In version 1.3.0 this dependency has a scope of `compile`

```
    <dependency>
      <groupId>com.yubico</groupId>
      <artifactId>yubico-util</artifactId>
      <version>1.4.0</version>
      <scope>runtime</scope>
    </dependency>
```

Workaround is to add `yubico-util` to your project's `pom.xml` without the scope
```
    <dependency>
      <groupId>com.yubico</groupId>
      <artifactId>yubico-util</artifactId>
      <version>1.4.0</version>
    </dependency>
```

**Comment by FlattestGuitar** [comment] 2019-09-30 12:08
Thanks @ralscha, that worked. 

Unfortunately on version `1.4.0` I'm getting the same error but for a different dep:
```
Dependency convergence error for com.upokecenter:cbor:3.4.0 paths to dependency are:
+-MY MODULE
  +-com.yubico:webauthn-server-core:1.4.0
    +-com.augustcellars.cose:cose-java:0.9.10
      +-com.upokecenter:cbor:3.4.0
and
+-MY MODULE
  +-com.yubico:yubico-util:1.4.0
    +-com.upokecenter:cbor:2.4.1```

**Comment by emlun** [comment] 2019-09-30 12:21
Ok, I think I see what's going on with that classpath issue. Between 1.3.0 and 1.4.0 I upgraded to using Gradle's [new dependency API][gradle-deps] that separates between API and implementation dependencies. The internal dependencies were previously defined in the `compile` configuration - since this project needs them to compile - which meant they also bled into the compile classpath of downstream projects depending on this library. Now, instead, they are declared as compile dependencies for the library and only as runtime dependencies of dependent projects since dependent projects don't need them to compile.

What part of the build hit that `class file for com.yubico.internal.util.json.JsonStringSerializable not found` error? Was it the normal compile step, or some introspection plugin like enforcer?

[gradle-deps]: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by FlattestGuitar** [comment] 2019-09-30 12:24
It was definitely a part of the normal compilation.

**Comment by emlun** [comment] 2019-09-30 12:25
Ok, I'll see if I can reproduce the issue.

**Comment by ralscha** [comment] 2019-09-30 12:29
In my application 
```
com.yubico.webauthn.data.ByteArray.getBytes()
```
throws the error during compilation.
```
 cannot access com.yubico.internal.util.json.JsonStringSerializable
  class file for com.yubico.internal.util.json.JsonStringSerializable not found
```

It only works when `yubico-util` is on the compile classpath.

**Comment by ralscha** [comment] 2019-09-30 12:31
Make sense that `PublicKeyCredentialType` that also throws this error because it implements `JsonStringSerializable` like `ByteArray`

**Comment by emlun** [comment] 2019-09-30 13:19
Ok, looks like the compilation issue is specific to Kotlin. The following code works fine in a Java project depending on `1.4.0`:

```
    @Test
    public void instantiateStuff() {
        ByteArray a = new ByteArray(new byte[] {1, 2, 3, 4});
        System.out.println(a);

        PublicKeyCredentialType b = PublicKeyCredentialType.PUBLIC_KEY;
        System.out.println(b);
    }

```

but the following does not work in a Kotlin project with equivalent setup:

```
    @Test fun byteArray() {
        val a = com.yubico.webauthn.data.ByteArray(byteArrayOf(1, 2, 3, 4))
        println(a)
        val b = PublicKeyCredentialType.PUBLIC_KEY
        println(b)
    }
```

It does work with `1.3.0`, though.

I guess I'll have to revert the "upgrade" to the new Gradle API, then.

**Comment by ralscha** [comment] 2019-09-30 13:32
For me the compiler error occurs in a Java application

**Comment by FlattestGuitar** [comment] 2019-09-30 13:34
@emlun try to turn that `PUBLIC_KEY` into a static import or do `a.getBytes()`. It should fail on both counts. I'm not sure how Java works all this out (I'm new to this D:), but it seems to be unable to actually access that class somehow. 

In your Kotlin code you use `byteArrayOf()`, a method that would likely also cause a failure if you used it in your Java code.

**Comment by emlun** [comment] 2019-09-30 13:51
Ah yes... the `com.yubico.internal.util.JsonStringSerializable` _is_ exposed in the API, so of course it needs to be on the API classpath. I'll push out a bugfix release candidate as soon as I can. Perhaps that can also resolve the Maven Enforcer issue by bumping the cbor dependency to major version 3.

**Comment by emlun** [comment] 2019-10-02 15:41
@FlattestGuitar @ralscha Version `1.4.1-RC1` is out now on Maven Central, please try if that works!

**Comment by ralscha** [comment] 2019-10-02 17:04
This solves my compile problem. Thanks.

**Comment by FlattestGuitar** [comment] 2019-10-03 09:22
Nope.

```
  [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-convergence) @ my-module ---
  [WARNING] 
  Dependency convergence error for com.upokecenter:cbor:3.6.0 paths to dependency are:
  +-my.module
    +-com.yubico:webauthn-server-core:1.4.1-RC1
      +-com.yubico:yubico-util:1.4.1-RC1
        +-com.upokecenter:cbor:3.6.0
  and
  +-my.module
    +-com.yubico:webauthn-server-core:1.4.1-RC1
      +-com.augustcellars.cose:cose-java:0.9.10
        +-com.upokecenter:cbor:3.4.0
  
  [WARNING] 
  Dependency convergence error for com.github.peteroupc:numbers:1.4.2 paths to dependency are:
  +-my.module
    +-com.yubico:webauthn-server-core:1.4.1-RC1
      +-com.yubico:yubico-util:1.4.1-RC1
        +-com.upokecenter:cbor:3.6.0
          +-com.github.peteroupc:numbers:1.4.2
  and
  +-my.module
    +-com.yubico:webauthn-server-core:1.4.1-RC1
      +-com.augustcellars.cose:cose-java:0.9.10
        +-com.github.peteroupc:numbers:1.2.1
```

**Comment by emlun** [comment] 2019-10-03 09:56
Ok. Can you give me a POM (preferably minimal) for reproducing the issue?

**Comment by FlattestGuitar** [comment] 2019-10-03 10:37
This is a pom for a quick project I whipped up with Boot Initializr:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.9.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yubico</groupId>
            <artifactId>webauthn-server-core</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                <execution>
                    <id>enforce</id>
                    <configuration>
                        <rules>
                            <dependencyConvergence/>
                        </rules>
                    </configuration>
                    <goals>
                        <goal>enforce</goal>
                    </goals>
                </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

Running `mvn clean compile` from project root will produce this:
```
[WARNING] 
Dependency convergence error for com.upokecenter:cbor:2.4.1 paths to dependency are:
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.yubico:webauthn-server-core:1.4.0
    +-com.yubico:yubico-util:1.4.0
      +-com.upokecenter:cbor:2.4.1
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.yubico:webauthn-server-core:1.4.0
    +-com.augustcellars.cose:cose-java:0.9.10
      +-com.upokecenter:cbor:3.4.0

[WARNING] 
Dependency convergence error for com.github.peteroupc:numbers:0.2.1 paths to dependency are:
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.yubico:webauthn-server-core:1.4.0
    +-com.yubico:yubico-util:1.4.0
      +-com.upokecenter:cbor:2.4.1
        +-com.github.peteroupc:numbers:0.2.1
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.yubico:webauthn-server-core:1.4.0
    +-com.augustcellars.cose:cose-java:0.9.10
      +-com.github.peteroupc:numbers:1.2.1

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

**Comment by emlun** [comment] 2019-10-03 10:48
Perfect, thanks! I'll investigate.

**Comment by emlun** [comment] 2019-10-03 12:14
Reducing the example POM to depend only on `com.augustcellars.cose:cose-java:0.9.10` exhibits the same problem:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ demo ---
[WARNING]
Dependency convergence error for com.github.peteroupc:numbers:0.4.0 paths to dependency are:
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.augustcellars.cose:cose-java:0.9.10
    +-com.upokecenter:cbor:3.4.0
      +-com.github.peteroupc:numbers:0.4.0
and
+-com.example:demo:0.0.1-SNAPSHOT
  +-com.augustcellars.cose:cose-java:0.9.10
    +-com.github.peteroupc:numbers:1.2.1

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

So this particular issue is inherited from [cose-java](/cose-wg/COSE-JAVA) and can't be fixed on our end. I've opened cose-wg/COSE-JAVA#92 to try to get it fixed upstream.

Thank you both for reporting and helping to narrow down these problems!

**Closed by emlun** 2019-10-03 12:14 UTC
Labels: bug
